name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "0.7.17"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      # pyinstaller worked fine on linux but causes anti-virus alert on win11, thus using nuitka
      - name: Build executable
        run: |
          uv run nuitka src/main.py \
          --mode=app \
          --output-dir=dist \
          --include-data-dir=assets=assets \
          --include-module=tcod

      # # Build python script into a single execute or app folder (macOS)
      # - name: Build Executable
      #   uses: Nuitka/Nuitka-Action@v1.3
      #   with:
      #     nuitka-version: 2.7.11
      #     script-name: src/main.py
      #     mode: app
      #     include-data-dir: |
      #       assets=assets
      #     output-dir: dist
      #     include-module: |
      #       tcod

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            dist/*.exe
            dist/*.bin
            dist/*.app/**/*
            dist/*.dist/**/*
          include-hidden-files: true
