name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        # os: [ ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "0.7.17"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Build
        run: uv run pyinstaller src/main.py -n tstt_rl --noconfirm

      - name: Include assets in distribution
        run: cp -r assets dist/tstt_rl

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            dist/tstt_rl/**/*
          include-hidden-files: true
