name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]
        # os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "0.7.17"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Download
        run: |
          $downloadUrl = "https://github.com/libsdl-org/SDL/releases/download/release-3.2.16/SDL3-3.2.16-win32-x64.zip"
          $zipPath = "$PSScriptRoot\SDL3-3.2.16-win32-x64.zip"
          $extractPath = $PSScriptRoot

          Invoke-WebRequest $downloadUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $extractPath -Force
          Get-ChildItem -Force

      # nuitka and pyinstaller worked fine on linux but causes anti-virus alert on win11. Now using cx_freeze. At the very least cx_freeze is much faster to compile.
      - name: Build executable
        run: uv run python setup.py build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tstt_rl_${{ runner.os }}
          path: |
            build/*
          include-hidden-files: true
